using System.Collections.Generic;

namespace POD_Banking.Base
{
    public static class PodParameterName
    {
        public static Dictionary<string, string> ParametersName = new Dictionary<string, string>
        {
            {"Token", "_token_"},
            {"ApiToken", "token"},
            {"TokenIssuer", "_token_issuer_"},
            {"ScVoucherHash", "scVoucherHash"},
            {"ScApiKey", "scApiKey"},
            {"UserName", "UserName"},
            {"CardNumber", "CardNumber"},
            {"Timestamp", "Timestamp"},
            {"Signature", "signature"},
            {"SrcCardNumber", "SrcCardNumber"},
            {"DestCardNumber", "DestCardNumber"},
            {"Email", "Email"},
            {"Amount", "Amount"},
            {"Cvv2", "Cvv2"},
            {"Password", "Password"},
            {"ExpireMonth", "ExpireMonth"},
            {"ExpireYear", "ExpireYear"},
            {"AuthorizationCode", "AuthorizationCode"},
            {"CardName", "CardName"},
            {"SrcComment", "SrcComment"},
            {"DestComment", "DestComment"},
            {"OriginalAddress", "OriginalAddress"},
            {"WithReferenceNumber", "WithReferenceNumber"},
            {"ExtraData", "JsonData"},
            {"SourceCardNumber", "SourceCardNumber"},
            {"SourceDepositNumber", "SourceDepositNumber"},
            {"DestinationCardNumber", "DestinationCardNumber"},
            {"MinAmount", "MinAmount"},
            {"MaxAmount", "MaxAmount"},
            {"StartDate", "StartDate"},
            {"EndDate", "EndDate"},
            {"RefrenceNumber", "RefrenceNumber"},
            {"SequenceNumber", "SequenceNumber"},
            {"SourceNote", "SourceNote"},
            {"DestinationNote", "DestinationNote"},
            {"DepositNumber", "DepositNumber"},
            {"Sheba", "Sheba"},
            {"ShenaseVariz", "ShenaseVariz"},
            {"Deposit", "Deposit"},
            {"ChequeNumber", "ChequeNumber"},
            {"BankCode", "BankCode"},
            {"ChequeStatus", "ChequeStatus"},
            {"StartSubmissionDate", "StartSubmisionDate"},
            {"EndSubmissionDate", "EndSubmissionDate"},
            {"RowCount", "RowCount"},
            {"FirstIndex", "FirstIndex"},
            {"Count", "Count"},
            {"SourceSheba", "SourceSheba"},
            {"DestDepositNumber", "DestDepositNumber"},
            {"DestSheba", "DestSheba"},
            {"DestFirstName", "DestFirstName"},
            {"DestLastName", "DestLastName"},
            {"SourceComment", "SourceComment"},
            {"PaymentId", "PaymentId"},
            {"Date", "Date"},
            {"BillNumber", "BillNumber"},
            {"TransferMoneyBillNumber", "TransferMoneyBillNumber"},
            {"FileUniqueIdentifier", "FileUniqueIdentifier"},
            {"BatchPayaItemInfos", "BatchPayaItemInfos"},
            {"BeneficiaryFullName", "BeneficiaryFullName"},
            {"Description", "Description"},
            {"DestShebaNumber", "DestShebaNumber"}
        };
    }
}

